### ISSUE TITLE
printing shell command to terminal makes it look like there is an error message even when spacegraphcats is running fine

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#224]
I recently initiated a spacegraphcats run and received the following output to my terminal:

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	bcalm_catlas_input
	1	bcalm_cdbg
	1	build_catlas
	1	make_contigs_kmer_index
	1	search
	5

[Tue Jun 25 14:07:26 2019]
rule bcalm_cdbg:
    input: bcalm.CSM67UFZ.k51.inputlist.txt
    output: CSM67UFZ/bcalm.CSM67UFZ.k51.unitigs.fa
    jobid: 4
    wildcards: catlas_base=CSM67UFZ, ksize=51

(bcalm -in bcalm.CSM67UFZ.k51.inputlist.txt -out CSM67UFZ/bcalm.CSM67UFZ.k51 -kmer-size 51 -abundance-min 1 >& CSM67UFZ/bcalm.CSM67UFZ.k51.unitigs.fa.log.txt && rm -f CSM67UFZ/bcalm.CSM67UFZ.k51.{h5,unitigs.fa.glue*}) || printf '**\n**\n** Cannot run BCALM 2! Please install it and make sure it is on your path!\n**\n**\n'
```

I didn't think twice, pressed control c, ran `conda install bcalm`, and received a message that `bcalm` was already installed. 

Then I ran `bcalm` and received the expected help message. 

I then realized that I had not received an error message about `bcalm`, but that this command would trigger the error message if I did not have bcalm in my path.

**Comment by taylorreiter** [comment]
I also just received a `Segmentation fault: 11`, I'm pretty sure from running out of memory, but the error message about `bcalm` not being installed still prints to the screen:

```
[Tue Jun 25 14:07:26 2019]
rule bcalm_cdbg:
    input: bcalm.CSM67UFZ.k51.inputlist.txt
    output: CSM67UFZ/bcalm.CSM67UFZ.k51.unitigs.fa
    jobid: 4
    wildcards: catlas_base=CSM67UFZ, ksize=51

(bcalm -in bcalm.CSM67UFZ.k51.inputlist.txt -out CSM67UFZ/bcalm.CSM67UFZ.k51 -kmer-size 51 -abundance-min 1 >& CSM67UFZ/bcalm.CSM67UFZ.k51.unitigs.fa.log.txt && rm -f CSM67UFZ/bcalm.CSM67UFZ.k51.{h5,unitigs.fa.glue*}) || printf '**\n**\n** Cannot run BCALM 2! Please install it and make sure it is on your path!\n**\n**\n'
/bin/bash: line 1: 66318 Segmentation fault: 11  bcalm -in bcalm.CSM67UFZ.k51.inputlist.txt -out CSM67UFZ/bcalm.CSM67UFZ.k51 -kmer-size 51 -abundance-min 1 >&CSM67UFZ/bcalm.CSM67UFZ.k51.unitigs.fa.log.txt
**
**
** Cannot run BCALM 2! Please install it and make sure it is on your path!
**
**
Waiting at most 3 seconds for missing files.
```

`bcalm` was definitely installed and running, as I received some bcalm output files:
```
$ ls CSM67UFZ
bcalm.CSM67UFZ.k51.h5                         bcalm.CSM67UFZ.k51.unitigs.fa.doubledKmers.3  bcalm.CSM67UFZ.k51.unitigs.fa.glue.1          bcalm.CSM67UFZ.k51.unitigs.fa.glue.3
bcalm.CSM67UFZ.k51.unitigs.fa.doubledKmers.2  bcalm.CSM67UFZ.k51.unitigs.fa.glue.0          bcalm.CSM67UFZ.k51.unitigs.fa.glue.2          bcalm.CSM67UFZ.k51.unitigs.fa.log.txt
```

**Comment by susheelbhanu** [comment]
I have the same issue - is this normal behaviour and to be ignored? Thanks..

**Comment by ctb** [comment]
If it all runs, yes :).  I have a new PR that should make things a lot clearer.

On Thu, Jan 23, 2020 at 12:38:31PM -0800, Susheel Bhanu Busi wrote:
> I have the same issue - is this normal behaviour and to be ignored? Thanks.. 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spacegraphcats/spacegraphcats/issues/224#issuecomment-577865913
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
this is related to #260 and fixed? in #261, which is not yet merged.

**Comment by susheelbhanu** [comment]
Hahah perfect. It's running for the moment, so will let you know in a few hours. Thanks @ctb

**Comment by ctb** [comment]
yay!

**Comment by susheelbhanu** [comment]
Alright, here's an update. It's been nearly 10 hours, and bcalm was still running. I realised that I did not 'trim the kmers', so was looking for the ```trim-low-abund.py``` script. Can't seem to find it in any of the directories. I cloned the git repository, so is there something I'm missing?

**Comment by ctb** [comment]
(moved trim-low-abund conversation to https://github.com/spacegraphcats/spacegraphcats/issues/262  - thanks for asking!)

**Comment by ctb** [comment]
This issue should be fixed in #261.

**Comment by taylorreiter** [comment]
this still doesn't look great...I thought BCALM threw and error just now. 
Although I am on the branch `dominator_abund`. Printing below...is it different on main branch?

```
[Tue Dec  8 13:40:18 2020]
Finished job 6.
1 of 7 steps (14%) done

[Tue Dec  8 13:40:18 2020]
rule bcalm_cdbg:
    input: rgnv_nbhd_k31/bcalm.inputlist.txt
    output: rgnv_nbhd_k31/bcalm.unitigs.fa
    log: rgnv_nbhd_k31_r5/bcalm.rgnv_nbhd_k31_r5.log.txt
    jobid: 4


        # can we run it?
        bcalm >& /dev/null ||             (printf "**
** ERROR: Cannot run bcalm! Is it installed?
**
";              false)

        # ok, run bcalm for real; use tee to both save & output stderr,
        # per https://stackoverflow.com/questions/692000/how-do-i-write-stderr-to-a-file-while-using-tee-with-a-pipe
        bcalm -in rgnv_nbhd_k31/bcalm.inputlist.txt -out rgnv_nbhd_k31/bcalm            -kmer-size 31 -abundance-min 1 > >(tee -a rgnv_nbhd_k31_r5/bcalm.rgnv_nbhd_k31_r5.log.txt >& 2)

        # remove large temp files: .h5, unitig glue files
        rm -f rgnv_nbhd_k31/bcalm.{h5,unitigs.fa.glue*}

setting storage type to hdf5
```

**Comment by ctb** [comment]
well, the error message IS in the shell: block, fo' sure, and that's what -p displays. 😄 

I think the only ways to remove it from the command would be to:
* not run with `-p`
* have a helper script that is run instead of having a large `shell:`
* or, well, normalize running this specifically in a conda environment so the failure comes earlier, if bcalm cannot be installed.

thoughts?

**Comment by taylorreiter** [comment]
could add an extra rule before `rule bcalm_cdbg` that contained:

```
shell:'''
 bcalm >& /dev/null ||             (printf "**
** ERROR: Cannot run bcalm! Is it installed?
**
";              false)

touch bcalm_is_installed.txt
```

As one of the first rules, so if it succeeds it will do so quickly and won't linger on that message for a long time as it currently does in `rule bcalm_cdbg`. And `bcalm_cdbg` could rely on `bcalm_is_installed.txt` as input.

**Comment by ctb** [comment]
On Wed, Dec 09, 2020 at 12:33:01PM -0800, Taylor Reiter wrote:
> touch bcalm_is_installed.txt

note! output blocks can have `touch('.bcalm_is_installed')`!

**Comment by ctb** [comment]
with the update to the docs to use conda, I think the right thing to do here is to simply remove the check for bcalm install. down the road we will probably enable `--use-conda` #290 by default, too, but not today :)
